name: Update dist

on:
  push:
    branches:
      - master
      - main

concurrency:
  group: update-dist-${{ github.ref }}
  cancel-in-progress: true

jobs:
  update-dist:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure git user
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Install dependencies
        run: |
          yarn install --frozen-lockfile

      - name: Update dist
        run: |
          yarn package

      - name: Commit changes
        run: |
          git add dist && \
          git commit -m "feat: Update dist" && \
          git push || \
          echo "No changes to commit" || true
